injectEnvironmentFiles:
  - .env?

# todo: switch to pnp
nodeLinker: node-modules

#npmScopes:
#  share-meals:
#    npmAlwaysAuth: true
#    npmAuthToken: "${GITHUB_PAT}"
#    npmRegistryServer: "https://npm.pkg.github.com"

packageExtensions:
  "@firebase/database@*":
    dependencies:
      "@firebase/app": "*"
      "@firebase/app-types": "*"
  "@ionic/react-router@*":
    dependencies:
      history: "*"
